jaffle_shop:
  target: default
  outputs:
    default:
      type: sqlite
      database: any
      schema: main
      threads: 1
      schemas_and_paths:
        main: target/main.db
      schema_directory: target
